resolver: ghc-8.2.1
extra-deps:
  - adjunctions-4.3
  - async-2.1.1.1
  - base-orphans-0.6
  - bifunctors-5.4.2
  - blaze-builder-0.4.0.2
  - cabal-doctest-1.0.2
  - call-stack-0.1.0
  - comonad-5.0.2
  - contravariant-1.4
  - data-default-class-0.1.2.0
  - dependent-map-0.2.4.0
  - dependent-sum-0.4
  - distributive-0.5.3
  - exceptions-0.8.3
  - fail-4.9.0.0
  - free-4.12.4
  - hashable-1.2.6.1
  - kan-extensions-5.0.2
  - lens-4.15.4
  - microlens-0.4.8.1
  - microlens-mtl-0.1.11.0
  - microlens-th-0.4.1.1
  - mtl-2.2.1
  - parallel-3.2.1.1
  - parsec-3.1.11
  - pqueue-1.3.2.3
  - prelude-extras-0.4.0.3
  - primitive-0.6.2.0
  - profunctors-5.2.1
  - reactive-banana-1.1.0.1
  - reflection-2.1.2
  - semigroupoids-5.2.1
  - semigroups-0.18.3
  - StateVar-1.1.0.4
  - stm-2.4.4.1
  - tagged-0.8.5
  - text-1.2.2.2
  - th-abstraction-0.2.6.0
  - transformers-compat-0.5.1.4
  - unordered-containers-0.2.8.0
  - utf8-string-1.0.1.1
  - vault-0.3.0.7
  - vector-0.12.0.1
  - void-0.7.2
  - vty-5.17.1
